package proyectopoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static proyectopoo.archivos.obtenerCredenciales;

public class TareasAdmin extends javax.swing.JFrame {
    static boolean isAdmin;
    archivos ar = new archivos();
    ArrayList <String> tareasDisp=new <String> ArrayList();
    private Object objeto;
    String idTarea;
    trabajador worker = null;
    ArrayList <String> usersArch = new <String>ArrayList();

    
    
    public TareasAdmin (){
        initComponents();
    }
    public TareasAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
        
        initComponents();
        inicio();
    }
    
    public void inicio(){
        detallesLabel.setVisible(true);
        usersArch.addAll(ar.archivos(true));
        
        tareasDisp.addAll(ar.archivos(false));
        
        for(int i = 0; i < tareasDisp.size(); i++) {
            tareasCombo.addItem(tareasDisp.get(i).toString());
            asidtarea.addItem(tareasDisp.get(i).toString());
        }
        for(int i = 0; i < usersArch.size(); i++) {
            idtrabajadorcombo.addItem(usersArch.get(i).toString());
            asigTrabajadortxt.addItem(usersArch.get(i).toString());
            idtraAsigcombo1.addItem(usersArch.get(i).toString());
        }
        deteleb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        exitTareaB = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tareasCombo = new javax.swing.JComboBox();
        detallesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text1 = new javax.swing.JTextPane();
        cargarTb1 = new javax.swing.JButton();
        cargarTb2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        idNewlbl = new javax.swing.JLabel();
        apePatNewlbl = new javax.swing.JLabel();
        apePatNewlbl1 = new javax.swing.JLabel();
        nombreNewlbl1 = new javax.swing.JLabel();
        puestoNewlbl = new javax.swing.JLabel();
        paswordNewlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jname = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jpuesto = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        japepat = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        japemat = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jpasword = new javax.swing.JTextPane();
        agregarB = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jid1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        tarealbl = new javax.swing.JLabel();
        idtrabajorlbl = new javax.swing.JLabel();
        idtarealbl1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        idtareatxt = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        desctxt = new javax.swing.JTextPane();
        idtrabajorlbl1 = new javax.swing.JLabel();
        idtrabajadorcombo = new javax.swing.JComboBox();
        agregartareaB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tarealbl1 = new javax.swing.JLabel();
        idtrabajorlbl2 = new javax.swing.JLabel();
        idtarealbl2 = new javax.swing.JLabel();
        asigTrabajadortxt = new javax.swing.JComboBox();
        asidtarea = new javax.swing.JComboBox();
        estadocombo = new javax.swing.JComboBox();
        asignartareaB1 = new javax.swing.JButton();
        idtrabajorlbl3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tarealbl2 = new javax.swing.JLabel();
        idtrabajorlbl4 = new javax.swing.JLabel();
        idtraAsigcombo1 = new javax.swing.JComboBox();
        cargarTb = new javax.swing.JButton();
        idtrabajorlbl5 = new javax.swing.JLabel();
        deteleb = new javax.swing.JButton();
        mostrarRelatxt = new javax.swing.JTextField();
        actualizar1b = new javax.swing.JButton();
        estaditicasb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Inicio");

        exitTareaB.setText("Salir");
        exitTareaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitTareaBActionPerformed(evt);
            }
        });

        jLabel2.setText("Tareas Disponibles");

        tareasCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tareasComboActionPerformed(evt);
            }
        });

        detallesLabel.setText("Detalles de la tarea");

        jScrollPane1.setViewportView(Text1);

        cargarTb1.setText("cargar tareas");
        cargarTb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarTb1ActionPerformed(evt);
            }
        });

        cargarTb2.setText("cargar tareas");
        cargarTb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarTb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tareasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detallesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cargarTb2)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(cargarTb1)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tareasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detallesLabel))
                    .addComponent(cargarTb2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(cargarTb1)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );

        jLabel3.setText("agegar Usuario");

        idNewlbl.setText("id:");

        apePatNewlbl.setText("apellido paterno:");

        apePatNewlbl1.setText("apellido materno:");

        nombreNewlbl1.setText("nombre: ");

        puestoNewlbl.setText("puesto:");

        paswordNewlbl.setText("pasword:");

        jScrollPane2.setViewportView(jname);

        jScrollPane3.setViewportView(jpuesto);

        jScrollPane4.setViewportView(japepat);

        jScrollPane5.setViewportView(japemat);

        jScrollPane7.setViewportView(jpasword);

        agregarB.setText("agregar");
        agregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(jid1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puestoNewlbl)
                                    .addComponent(nombreNewlbl1)
                                    .addComponent(paswordNewlbl)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(apePatNewlbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(idNewlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(apePatNewlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregarB)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(idNewlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreNewlbl1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(apePatNewlbl)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(apePatNewlbl1)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(puestoNewlbl))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 28, Short.MAX_VALUE)
                                .addComponent(agregarB))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(paswordNewlbl)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tarealbl.setText("agregar tarea");

        idtrabajorlbl.setText("id trabajador");

        idtarealbl1.setText("id tarea:");

        jScrollPane6.setViewportView(idtareatxt);

        jScrollPane9.setViewportView(desctxt);

        idtrabajorlbl1.setText("desripcion");

        idtrabajadorcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtrabajadorcomboActionPerformed(evt);
            }
        });

        agregartareaB.setText("agregar");
        agregartareaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregartareaBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(idtrabajorlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(185, 185, 185))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregartareaB)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idtarealbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tarealbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idtrabajorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idtrabajadorcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tarealbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(idtarealbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtrabajorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtrabajadorcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(idtrabajorlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(agregartareaB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tarealbl1.setText("asignar tarea");

        idtrabajorlbl2.setText("estado");

        idtarealbl2.setText("id tarea:");

        asidtarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asidtareaActionPerformed(evt);
            }
        });

        estadocombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pendiente", "en progreso", "terminada", "entregada" }));
        estadocombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadocomboActionPerformed(evt);
            }
        });

        asignartareaB1.setText("asignar");
        asignartareaB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignartareaB1ActionPerformed(evt);
            }
        });

        idtrabajorlbl3.setText("id trabajador");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asignartareaB1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(idtarealbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(asidtarea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(idtrabajorlbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asigTrabajadortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tarealbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idtrabajorlbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estadocombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tarealbl1)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtarealbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asidtarea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asigTrabajadortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtrabajorlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtrabajorlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadocombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(asignartareaB1))
        );

        tarealbl2.setText("eliminar tarea");

        idtrabajorlbl4.setText("id trabajador");

        idtraAsigcombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtraAsigcombo1ActionPerformed(evt);
            }
        });

        cargarTb.setText("cargar tareas");
        cargarTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarTbActionPerformed(evt);
            }
        });

        idtrabajorlbl5.setText("tareas");

        deteleb.setText("eliminar tarea");
        deteleb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detelebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(tarealbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(idtrabajorlbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idtraAsigcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(idtrabajorlbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(62, 62, 62)
                                .addComponent(cargarTb))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deteleb))
                    .addComponent(mostrarRelatxt))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tarealbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtrabajorlbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtraAsigcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarTb)
                    .addComponent(idtrabajorlbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarRelatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deteleb)
                .addContainerGap())
        );

        actualizar1b.setText("actualizar");
        actualizar1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar1bActionPerformed(evt);
            }
        });

        estaditicasb.setText("generar estadisticas");
        estaditicasb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estaditicasbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(estaditicasb)
                        .addGap(65, 65, 65)
                        .addComponent(actualizar1b)
                        .addGap(92, 92, 92)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitTareaB)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exitTareaB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(actualizar1b)
                            .addComponent(estaditicasb))
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTareaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitTareaBActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitTareaBActionPerformed

    private void tareasComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tareasComboActionPerformed
        
    }//GEN-LAST:event_tareasComboActionPerformed

    private void agregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBActionPerformed
        
        trabajador newWorker = new trabajador(jid1.getText(),jname.getText(), japepat.getText(), japemat.getText(), jpuesto.getText(), jpasword.getText());
        System.out.println(jid1.getText());
        ar.crearWorker(jid1.getText());
        ar.llenarWorker(newWorker, jid1.getText());
        
    }//GEN-LAST:event_agregarBActionPerformed

    private void agregartareaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregartareaBActionPerformed

        String idtarea = idtareatxt.getText();
        String idtrabajador = idtrabajadorcombo.getSelectedItem().toString();
        String msj = desctxt.getText();
        archivos.crearArchRelacion(idtrabajador, idtarea+".txt", "pendiente");
        
        archivos.asignarDescripcion(idtarea, msj);

    }//GEN-LAST:event_agregartareaBActionPerformed

    private void asignartareaB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignartareaB1ActionPerformed
        
        String idtarea = asidtarea.getSelectedItem().toString();
        String idtrabajador = asigTrabajadortxt.getSelectedItem().toString();
        String estado=estadocombo.getSelectedItem().toString();
        archivos.crearArchRelacion(idtrabajador, idtarea, estado);
        
    }//GEN-LAST:event_asignartareaB1ActionPerformed

    private void asidtareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asidtareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asidtareaActionPerformed

    private void cargarTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarTbActionPerformed

        String idrelatra = idtraAsigcombo1.getSelectedItem().toString();
        ArrayList rela = new ArrayList();
        rela.addAll(archivos.obtenerRelacion(idrelatra));
        if(!rela.isEmpty()){
            mostrarRelatxt.setText("Estado: "+ rela.get(0)+ "   |    Nombre Tarea: " + rela.get(1));
            deteleb.setVisible(true);
        }else{
            mostrarRelatxt.setText("No hay tarea asignada");
        }
        
        
    }//GEN-LAST:event_cargarTbActionPerformed

    private void detelebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detelebActionPerformed
        
        String idrelatra = idtraAsigcombo1.getSelectedItem().toString();
        ArrayList rela = new ArrayList();
        
        rela.addAll(archivos.obtenerRelacion(idrelatra));
        
        archivos.eliminarTarea((String) rela.get(1));
        
        archivos.setArchRelacion(idrelatra);
    }//GEN-LAST:event_detelebActionPerformed

    private void idtraAsigcombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtraAsigcombo1ActionPerformed
        
        String idtrab = idtraAsigcombo1.getSelectedItem().toString();
        String id;
        ArrayList <String> userData = new <String> ArrayList();
        if(usersArch.contains(idtrab)){
            id = idtrab;
            userData.addAll(obtenerCredenciales(id, false));
            //worker.settrabajador(id, userData);
        }
        
    }//GEN-LAST:event_idtraAsigcombo1ActionPerformed

    private void estadocomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadocomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadocomboActionPerformed

    private void actualizar1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar1bActionPerformed
        usersArch.clear();
        tareasDisp.clear();
        
        usersArch.addAll(ar.archivos(true));
        tareasDisp.addAll(ar.archivos(false));
        
        idtrabajadorcombo.removeAllItems();
        tareasCombo.removeAllItems();
        asidtarea.removeAllItems();
        asigTrabajadortxt.removeAllItems();
        idtraAsigcombo1.removeAllItems();
        
        for(int i = 0; i < tareasDisp.size(); i++) {
            tareasCombo.addItem(tareasDisp.get(i).toString());
        }
        for(int i = 0; i < tareasDisp.size(); i++) {
            asidtarea.addItem(tareasDisp.get(i).toString());
        }
        for(int i = 0; i < usersArch.size(); i++) {
            idtraAsigcombo1.addItem(usersArch.get(i).toString());
        }
        for(int i = 0; i < usersArch.size(); i++) {
            idtrabajadorcombo.addItem(usersArch.get(i).toString());
        }
        for(int i = 0; i < usersArch.size(); i++) {

            asigTrabajadortxt.addItem(usersArch.get(i).toString());

        }
    }//GEN-LAST:event_actualizar1bActionPerformed

    private void idtrabajadorcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtrabajadorcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtrabajadorcomboActionPerformed

    private void cargarTb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarTb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarTb1ActionPerformed

    private void cargarTb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarTb2ActionPerformed
//        tareasCombo.removeAllItems();
//        for(int i = 0; i < tareasDisp.size(); i++) {
//            tareasCombo.addItem(tareasDisp.get(i).toString());
//        }
//        
        idTarea= tareasCombo.getSelectedItem().toString();
        Tarea tar = new Tarea();
        Text1.setText(tar.obtenerDescripcion(idTarea));
    }//GEN-LAST:event_cargarTb2ActionPerformed

    private void estaditicasbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estaditicasbActionPerformed
       Tarea.estadisticas();
    }//GEN-LAST:event_estaditicasbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareasAdmin().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Text1;
    private javax.swing.JButton actualizar1b;
    private javax.swing.JButton agregarB;
    private javax.swing.JButton agregartareaB;
    private javax.swing.JLabel apePatNewlbl;
    private javax.swing.JLabel apePatNewlbl1;
    private javax.swing.JComboBox asidtarea;
    private javax.swing.JComboBox asigTrabajadortxt;
    private javax.swing.JButton asignartareaB1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cargarTb;
    private javax.swing.JButton cargarTb1;
    private javax.swing.JButton cargarTb2;
    private javax.swing.JTextPane desctxt;
    private javax.swing.JLabel detallesLabel;
    private javax.swing.JButton deteleb;
    private javax.swing.JButton estaditicasb;
    private javax.swing.JComboBox estadocombo;
    private static javax.swing.JButton exitTareaB;
    private javax.swing.JLabel idNewlbl;
    private javax.swing.JLabel idtarealbl1;
    private javax.swing.JLabel idtarealbl2;
    private javax.swing.JTextPane idtareatxt;
    private javax.swing.JComboBox idtraAsigcombo1;
    private javax.swing.JComboBox idtrabajadorcombo;
    private javax.swing.JLabel idtrabajorlbl;
    private javax.swing.JLabel idtrabajorlbl1;
    private javax.swing.JLabel idtrabajorlbl2;
    private javax.swing.JLabel idtrabajorlbl3;
    private javax.swing.JLabel idtrabajorlbl4;
    private javax.swing.JLabel idtrabajorlbl5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane japemat;
    private javax.swing.JTextPane japepat;
    private javax.swing.JTextPane jid1;
    private javax.swing.JTextPane jname;
    private javax.swing.JTextPane jpasword;
    private javax.swing.JTextPane jpuesto;
    private javax.swing.JTextField mostrarRelatxt;
    private javax.swing.JLabel nombreNewlbl1;
    private javax.swing.JLabel paswordNewlbl;
    private javax.swing.JLabel puestoNewlbl;
    private javax.swing.JLabel tarealbl;
    private javax.swing.JLabel tarealbl1;
    private javax.swing.JLabel tarealbl2;
    private javax.swing.JComboBox tareasCombo;
    // End of variables declaration//GEN-END:variables
}
